export const Constants = {
  BIRTH_MONTH: 7,
  BIRTH_YEAR: 1996,
  LIFE_EXPECTANCY: 90,
  START_MONTH: 7,
  START_YEAR: 2024,
  RETIREMENT_AGE: 55,
  RETIREMENT_MONTHLY_WITHDRAWAL: 5000,
  INFLATION_RATE: 0.03,
};
